### ISSUE TITLE
Numpy >= 1.24 breaks training

### ISSUE THREAD

**Issue by feiticeir0** [Seeed-Studio/yolov5-swift#31]
### Search before asking

- [X] I have searched the YOLOv5-Swift [issues](https://github.com/Seeed-Studio/yolov5-swift/issues) and found no similar bug report.

### YOLOv5-Swift Component

Training

### Bug

When training in the local computer - NOT USING COLAB - when starting the train session, I get the following error:

`optimizer: SGD with parameter groups 75 weight (no decay), 79 weight, 79 bias
train: Scanning 'C:\Users\bvsantos\Scripts\visionAI\yolov5-swift\..\content\datasets\Apple-Detection-1\train\labels.cache' images and labels... 553 found, 0 missing, 0 empty,
Traceback (most recent call last):
  File "C:\Users\bvsantos\Scripts\visionAI\yolov5-swift\train.py", line 646, in <module>
    main(opt)
  File "C:\Users\bvsantos\Scripts\visionAI\yolov5-swift\train.py", line 542, in main
    train(opt.hyp, opt, device, callbacks)
  File "C:\Users\bvsantos\Scripts\visionAI\yolov5-swift\train.py", line 225, in train
    train_loader, dataset = create_dataloader(train_path, imgsz, batch_size // WORLD_SIZE, gs, single_cls,
  File "C:\Users\bvsantos\Scripts\visionAI\yolov5-swift\utils\datasets.py", line 100, in create_dataloader
    dataset = LoadImagesAndLabels(path, imgsz, batch_size,
  File "C:\Users\bvsantos\Scripts\visionAI\yolov5-swift\utils\datasets.py", line 443, in __init__
    bi = np.floor(np.arange(n) / batch_size).astype(np.int)  # batch index
  File "C:\Users\bvsantos\Scripts\visionAI\lib\site-packages\numpy\__init__.py", line 313, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'inf'?`

when installing the requirements.txt, the numpy version installed is 1.25.1 

After version 1.20, np.int is deprecated and removed after 1.24 . 
This is using the CPU .  

### Environment

- YOLOv5-Swift
- Windows 11
- Python 3.10.4

### Minimal Reproducible Example

python.exe train.py --img 192 --batch 64 --epochs 100 --data .\content\datasets\Apple-Detection-1\data.yaml --cfg yolov5n6-xiao.yaml --weights yolov5n6-xiao.pt --name yolov5n6-results --cache

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by feiticeir0** [comment]
To solve this, we need to use conda - not Python env - and create an environment with Python3.9 .
```
conda create -n visionAI python=3.9
conda activate visionAI
```
And then we can use pip to install the requirements
`pip install -r requirements.txt`

And then, it works.
